export const ROUTE_NAMES = {
  HOME: "home",
  ABOUT: "about",
  PROJECTS: "projects",
  PROJECT_DETAIL: "project-detail",
  BLOG: "blog",
  BLOG_DETAIL: "blog-detail",
  CONTACT: "contact",
  LOGIN: "login",
  ERROR_404: "error-404",
  SETTINGS: "settings",
  DASHBOARD_PRIVATE: "dashboard-private",
  PROJECT_CMS: "project-cms",
  BLOG_CMS: "blog-cms",
  NOTES: "notes",
  CASHFLOW: "cashflow",
  HABITS: "habits",
  EMAIL_SCHEDULER: "email-scheduler",
  GOALS: "goals",
  AI_CHAT: "ai-chat",
  LOGOUT: "logout",
} as const;

export const ROUTE_PATHS = {
  HOME: "/",
  ABOUT: "/about",
  PROJECTS: "/projects",
  PROJECT_DETAIL: "/projects/:slug",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/:slug",
  CONTACT: "/contact",
  LOGIN: "/login",
  SETTINGS: "/private/settings",
  DASHBOARD_PRIVATE: "/private/dashboard",
  PROJECT_CMS: "/private/projects",
  BLOG_CMS: "/private/blogs",
  NOTES: "/private/notes",
  CASHFLOW: "/private/cashflow",
  HABITS: "/private/habits",
  EMAIL_SCHEDULER: "/private/emails",
  GOALS: "/private/goals",
  AI_CHAT: "/private/ai-chat",
  LOGOUT: "/logout",

  ERROR_404: "/:pathMatch(.*)*",
} as const;
